# Site settings
name: Wellington Irish Sessions
email: archive@lpnz.org
author: archive@lpnz.org
keywords: irish, traditional, music, jigs, reels, polkas, craic
description: Irish trad tune archive

# Parameters embedded in site
slowsession_time: '7:30 to 8:30'
#slowsession_time: "Please check back when the world is normal!"
session_time: '8:45 to late'
#session_time: "Please check back when the world is normal!"

# no of tunes to show in latest.md etc
latest_tunes_max: 20
slow_tunes_max: 100
reg_tunes_max: 20

# Only use this if you are serving your site via Github Pages
github:
    url: 'https://wellington.session.nz'

header: yes
header_image: images/banner.jpg

# Exclude our ruby stuff and other dirs
exclude:
    [
        .bundle,
        bin,
        vendor,
        Gemfile,
        Gemfile.lock,
        Rakefile,
        s3_website.yml,
        .last_optimized,
        _scripts,
        documentation,
        archive,
        mp3,
        tunebooks,
    ]

# Build settings
markdown: kramdown
kramdown:
    input: GFM

destination: _site

# Needed?
feed:
    path: atom.xml

# Compress our Css
sass:
    style: :compressed

# Needed?
permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
#google_universal_analytics: UA-77351761-1
#google_universal_analytics: G-SPNPRLXLS4
#google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user: WellingtonSession
# default FB id
facebook_app_id: 966242223397117
facebook_locale: en_US
facebook_page: https://www.facebook.com/groups/WellingtonSession/
facebook_image: /images/pubscene-small.jpg

# Needed?
# Twitter Cards
twitter_user:
twitter_card: false
twitter_image: #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

#
# Additions for transition or split site working like the DEV site
#
mp3_host: https://mp3.session.nz # leave blank if mp3 files are served from THIS SERVER
tunebooks_host: https://mp3.session.nz # leave blank if tunebook files are served from THIS SERVER
js_host: # leave blank if js files are served from THIS SERVER

collections:
    tunes:
        output: true

    northernfiddler:
        output: true

    obrientunes:
        output: true

    pottstunes:
        output: true

    sets:
        output: true

defaults:
    - scope:
          path: '_tunes'
      values:
          layout: 'tunepage'
          permalink: /tunes/:title:output_ext
    - scope:
          path: '_northernfiddler'
      values:
          layout: 'tunepage-northernfiddler'
          permalink: /northernfiddler/:title:output_ext
    - scope:
          path: '_obrientunes'
      values:
          layout: 'tunepage-obrien'
          permalink: /obrientunes/:title:output_ext
    - scope:
          path: '_pottstunes'
      values:
          layout: 'tunepage-potts'
          permalink: /pottstunes/:title:output_ext
    - scope:
          path: '_sets'
      values:
          layout: 'setpage'
          permalink: /sets/:title:output_ext
